# @Author: Adithya
# @Date:   2025-06-27
# @Last Modified by:   Adithya
# @Last Modified time: 2025-06-27
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - finby

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: |
          # Remove existing lock file and node_modules to start fresh
          rm -rf node_modules package-lock.json
          # Generate new lock file and install dependencies
          npm install --legacy-peer-deps

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build application
        run: npm run build

      - name: Run tests
        run: npm run test --if-present

      - name: Create deployment package
        run: |
          # Create a clean deployment package with only necessary files
          mkdir -p deploy-package
          cp -r .next deploy-package/
          cp -r public deploy-package/
          cp package*.json deploy-package/
          cp -r prisma deploy-package/
          cp -r node_modules deploy-package/
          
          # Create zip from the deployment package
          cd deploy-package
          zip -r ../release.zip .
          cd ..

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0ABEFF01672948D394D2136134DDDE88 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_86599C7AE4BF4484B920617B2D3955BA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4071C46A81DE48D593451C7AD3E8AE45 }}
       
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'finby'
          slot-name: 'Production'
          package: .