# @Author: Adithya
# @Date:   2025-06-27
# @Last Modified by:   Adithya
# @Last Modified time: 2025-06-27
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - finby

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install --force

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production

      - name: Run tests (if present)
        run: npm run test --if-present

      - name: Create deployment package
        run: |
          # Create a clean deployment directory
          mkdir deployment-package
          
          # Copy necessary files for production
          cp -r .next deployment-package/
          cp -r public deployment-package/ 2>/dev/null || true
          cp package*.json deployment-package/
          cp next.config.* deployment-package/ 2>/dev/null || true
          
          # Copy Prisma files if they exist
          cp -r prisma deployment-package/ 2>/dev/null || true
          
          # Create a production-only package.json in deployment
          cd deployment-package
          
          # Install only production dependencies
          npm ci --only=production --legacy-peer-deps
          
          # Generate Prisma client for production
          npx prisma generate 2>/dev/null || true
          
          # Create the zip file
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0ABEFF01672948D394D2136134DDDE88 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_86599C7AE4BF4484B920617B2D3955BA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4071C46A81DE48D593451C7AD3E8AE45 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'finby'
          slot-name: 'Production'
          package: .
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NODE_ENV: production